language: python
python:
- '3.5'
- '3.6'
- 'nightly'
install:
- python setup.py install
- pip install coveralls
script:
- python setup.py test
after_success:
- coveralls
- echo "SUCCESS IN ENV = $ENV"
